update hicmap

diff --git a/bin/hicmap b/bin/hicmap
--- a/bin/hicmap
+++ b/bin/hicmap
@@ -20,15 +20,14 @@ Map and processing Hi-C reads
 (4) pair up two ends and filter invalid hic pairs;
 (5) remove PCR duplication using Picard - MarkDuplicates;
 
-usage: hicmap [-h] [-t THREADS] [-m MAX_MEM] [-f FASTQ1] [-r FASTQ2] [-p MarkDuplicates.jar] [-n PREFIX] [-g BWA_GENOME] [-c CUT_SITES] [-m MIN_INSERT_SIZE]
+usage: hicmap [-h] [-t THREADS] [-f FASTQ1] [-r FASTQ2] [-p MarkDuplicates.jar] [-n PREFIX] [-g BWA_GENOME] [-c CUT_SITES] [-m MIN_INSERT_SIZE]
 
 Example:
-hicmap -t 10 -m 8G -f data/demo_R1.fastq.bz2 -r data/demo_R2.fastq.bz2 -p Picard/MarkDuplicates.jar -n demo -g /mnt/thumper/home/r3fang/data/Mus_musculus/UCSC/mm9/Sequence/BWAIndex/genome.fa -c mm9.MboI.bed -d 10000
+hicmap -t 10 -f data/demo_R1.fastq.bz2 -r data/demo_R2.fastq.bz2 -p Picard/MarkDuplicates.jar -n demo -g /mnt/thumper/home/r3fang/data/Mus_musculus/UCSC/mm9/Sequence/BWAIndex/genome.fa -c mm9.MboI.bed -d 10000
 
 Options:    
 	-h, --help           show this help message and exit.
 	-t  THREADS          threads [1].
-	-m  MAX_MEM          max memory usage [4G].
 	-f  FASTQ1           first mate of pair-end sequencing data [.fq/.fastq/.gz/.bz2].
 	-r  FASTQ2           second mate of pair-end sequencing data [.fq/.fastq/.gz/.bz2].
 	-p  MARK_DUPLICATE   path to picard MarkDuplicates.jar [bin/MarkDuplicates.jar].
@@ -36,20 +35,21 @@ Options:
 	-g  BWA_GENOME       BWA indexed reference genome.
 	-c  CUT_ENZ          restriction cutting enzyme files. 
 	-d  MIN_INSERT_SIZE  min insert size for valid "DIFFERENT-STRAND" pairs.
+
+Note: hicmap will requires at least 2GB memory usage.
 EOF
-} 
+}
+
+# MEM_FREE=$(cat /proc/meminfo | grep MemFree | awk '{print $2}')	
 
 # PART III default params
 THREADS=1
-MAX_MEM="4G"
-
 
 # PART IV receiving arguments
-while getopts ":t:m:f:r:p:n:g:c:d:" opt;
+while getopts ":t:f:r:p:n:g:c:d:" opt;
 do
 	case "$opt" in
 		t) THREADS=$OPTARG;;
-		m) MAX_MEM=$OPTARG;;
 		f) FASTQ1=$OPTARG;;
 		r) FASTQ2=$OPTARG;;
 		p) MARK_DUPLICATE=$OPTARG;;
@@ -58,48 +58,77 @@ do
 		c) CUT_ENZ=$OPTARG;;
 		d) MIN_INSERT_SIZE=$OPTARG;;
 		\?) usage
+			echo "error: unrecognized option -$OPTARG";
 			exit 1
 			;;
 	esac
 done
 
-if [ $# -lt 10 ] ; then
+if [ $# -lt 8 ] ; then
    usage
    echo "error: too few arguments"
    exit 1
 fi
 
+# THREADS
+if [ -z ${THREADS+x} ]; then 
+ 	echo "error: missing variable -t THREADS";
+ 	exit 1;
+fi
 re='^[0-9]+$'
 if ! [[ $THREADS =~ $re ]] ; then
    echo "error: '$THREADS' Not a number" >&2; 
    exit 1
 fi
 
-# check if input file exists
+# check if FASTQ1 file exists
+if [ -z ${FASTQ1+x} ]; then 
+ 	echo "error: missing variable -f FASTQ1";
+ 	exit 1;
+fi
 if [ ! -f $FASTQ1 ]; then
 	usage
     echo "error: '$FASTQ1' not exists.";
 	exit 1
 fi
 
+# check if FASTQ2 file exists
+if [ -z ${FASTQ2+x} ]; then 
+ 	echo "error: missing variable -f FASTQ2";
+ 	exit 1;
+fi
 if [ ! -f $FASTQ2 ]; then
 	usage
     echo "error: '$FASTQ2' not exists.";
 	exit 1
 fi
 
+# check if MARK_DUPLICATE file exists
+if [ -z ${MARK_DUPLICATE+x} ]; then 
+ 	echo "error: missing variable -p MARK_DUPLICATE";
+ 	exit 1;
+fi
 if [ ! -f $MARK_DUPLICATE ]; then
 	usage
     echo "error: '$MARK_DUPLICATE' not exists.";
 	exit 1
 fi
 
+# check if GENOME file exists
+if [ -z ${GENOME+x} ]; then 
+ 	echo "error: missing variable -g GENOME";
+ 	exit 1;
+fi
 if [ ! -f $GENOME ]; then
 	usage
     echo "error: '$GENOME' not exists.";
 	exit 1
 fi
 
+if [ -z ${CUT_ENZ+x} ]; then 
+ 	echo "error: missing variable -c $CUT_ENZ";
+ 	exit 1;
+fi
 if [ ! -f $CUT_ENZ ]; then
 	usage
     echo "error: '$CUT_ENZ' not exists.";
@@ -107,14 +136,15 @@ if [ ! -f $CUT_ENZ ]; then
 fi
 
 # check if input type
+if [ -z ${MIN_INSERT_SIZE+x} ]; then 
+ 	echo "error: missing variable -c $MIN_INSERT_SIZE";
+ 	exit 1;
+fi
 re='^[0-9]+$'
 if ! [[ $MIN_INSERT_SIZE =~ $re ]] ; then
    echo "error: '$MIN_INSERT_SIZE' Not a number" >&2; 
    exit 1
 fi
-
-MEM_FREE=$(cat /proc/meminfo | grep MemFree | awk '{print $2}')	
-
 
 echo $0 $* 2>&1 | tee $PREFIX.log 
 echo 2>&1 | tee -a $PREFIX.log
@@ -126,10 +156,8 @@ echo GENOME=$GENOME 2>&1 | tee -a $PREFIX.log
 echo CUTTER_SITES=$CUT_ENZ 2>&1 | tee -a $PREFIX.log
 echo PREFIX=$PREFIX 2>&1 | tee -a $PREFIX.log
 echo MIN_INSERT_SIZE=$MIN_INSERT_SIZE 2>&1 | tee -a $PREFIX.log
-echo MAX_MEMORY_USAGE=$MAX_MEM 2>&1 | tee -a $PREFIX.log
 
 echo 2>&1 | tee -a $PREFIX.log
-
 
 if [ ! -d $PREFIX\_tmp ]; then
 	mkdir $PREFIX\_tmp
@@ -139,10 +167,10 @@ echo "$(date) Step1. map reads and choose chemeric reads and non-uniquely mapped
 if [ ! -f $PREFIX\_tmp/$PREFIX\_R1.uniq.bam ]; then
 	if [ ${FASTQ1: -4} == ".bz2" ];
 	then
-		bwa mem -t $THREADS $GENOME <(bzip2 -dc $FASTQ1) | \
+		bwa mem -t $THREADS $GENOME <(bzip2 -dc $FASTQ1) 2> $PREFIX\_tmp/$PREFIX.R1.bwa.log | \
 			chimeric.pl - | samtools view -F 2048 -q 10 -bS - > $PREFIX\_tmp/$PREFIX\_R1.uniq.bam
 	else
-		bwa mem -t $THREADS $GENOME $FASTQ1 | \
+		bwa mem -t $THREADS $GENOME $FASTQ1 2> $PREFIX\_tmp/$PREFIX.R1.bwa.log | \
 			chimeric.pl - | samtools view -F 2048 -q 10 -bS - > $PREFIX\_tmp/$PREFIX\_R1.uniq.bam
 	fi
 else
@@ -152,10 +180,10 @@ fi
 if [ ! -f $PREFIX\_tmp/$PREFIX\_R2.uniq.bam ]; then
 	if [ ${FASTQ2: -4} == ".bz2" ];
 	then
-		bwa mem -t $THREADS $GENOME <(bzip2 -dc $FASTQ2) | \
+		bwa mem -t $THREADS $GENOME <(bzip2 -dc $FASTQ2) 2> $PREFIX\_tmp/$PREFIX.R2.bwa.log | \
 			chimeric.pl - | samtools view -F 2048 -q 10 -bS - > $PREFIX\_tmp/$PREFIX\_R2.uniq.bam
 	else
-		bwa mem -t $THREADS $GENOME $FASTQ2 | \
+		bwa mem -t $THREADS $GENOME $FASTQ2 2> $PREFIX\_tmp/$PREFIX.R2.bwa.log | \
 			chimeric.pl - | samtools view -F 2048 -q 10 -bS - > $PREFIX\_tmp/$PREFIX\_R2.uniq.bam
 	fi	
 else
@@ -170,8 +198,8 @@ then
 	samtools view -b -L $CUT_ENZ $PREFIX\_tmp/$PREFIX\_R1.uniq.bam > $PREFIX\_tmp/$PREFIX\_R1.uniq.filtered.bam &
 	samtools view -b -L $CUT_ENZ $PREFIX\_tmp/$PREFIX\_R2.uniq.bam > $PREFIX\_tmp/$PREFIX\_R2.uniq.filtered.bam &
 	wait
-	samtools sort -m $MAX_MEM -n $PREFIX\_tmp/$PREFIX\_R1.uniq.filtered.bam $PREFIX\_tmp/$PREFIX\_R1.uniq.filtered.sorted 
-	samtools sort -m $MAX_MEM -n $PREFIX\_tmp/$PREFIX\_R2.uniq.filtered.bam $PREFIX\_tmp/$PREFIX\_R2.uniq.filtered.sorted 
+	samtools sort -m 2G -n $PREFIX\_tmp/$PREFIX\_R1.uniq.filtered.bam $PREFIX\_tmp/$PREFIX\_R1.uniq.filtered.sorted 
+	samtools sort -m 2G -n $PREFIX\_tmp/$PREFIX\_R2.uniq.filtered.bam $PREFIX\_tmp/$PREFIX\_R2.uniq.filtered.sorted 
 	rm $PREFIX\_tmp/$PREFIX\_R1.uniq.filtered.bam	
 	rm $PREFIX\_tmp/$PREFIX\_R2.uniq.filtered.bam	
 fi
@@ -181,7 +209,7 @@ echo "$(date) Step4. pair up two ends and sort based on coordinates" 2>&1 | tee 
 if [ ! -f $PREFIX\_tmp/$PREFIX.uniq.filtered.paired.cis.longRange.sorted.bam ]; then
 	pair2mates -m $MIN_INSERT_SIZE -o $PREFIX\_tmp/$PREFIX.uniq.filtered.paired $PREFIX\_tmp/$PREFIX\_R1.uniq.filtered.sorted.bam $PREFIX\_tmp/$PREFIX\_R2.uniq.filtered.sorted.bam	
 	samtools view -h $PREFIX\_tmp/$PREFIX.uniq.filtered.paired.cis.bam | awk 'function abs(v) {return v < 0 ? -v : v} { if(substr($1, 1, 1)=="@" || abs($9) >= 10000) print }' | samtools view -bS - > $PREFIX\_tmp/$PREFIX.uniq.filtered.paired.cis.longRange.bam
-	samtools sort -m $MAX_MEM $PREFIX\_tmp/$PREFIX.uniq.filtered.paired.cis.longRange.bam $PREFIX\_tmp/$PREFIX.uniq.filtered.paired.cis.longRange.sorted
+	samtools sort -m 2G $PREFIX\_tmp/$PREFIX.uniq.filtered.paired.cis.longRange.bam $PREFIX\_tmp/$PREFIX.uniq.filtered.paired.cis.longRange.sorted
 	rm $PREFIX\_tmp/$PREFIX.uniq.filtered.paired.cis.longRange.bam
 else
 	printf 'warning: %s_tmp/%s.uniq.filtered.paired.bam already exist.\n'  "$PREFIX" "$PREFIX" 2>&1 | tee -a $PREFIX.log
@@ -190,7 +218,7 @@ fi
 echo 
 echo "$(date) Step6. Remove PCR duplication" 2>&1 | tee -a $PREFIX.log
 if [ ! -f $PREFIX.uniq.filtered.paired.cis.longRange.sorted.nodup.bam ]; then
-	java -Xmx$MAX_MEM -jar $MARK_DUPLICATE INPUT=$PREFIX\_tmp/$PREFIX.uniq.filtered.paired.cis.longRange.sorted.bam OUTPUT=$PREFIX.bam ASSUME_SORTED=true REMOVE_DUPLICATES=true VALIDATION_STRINGENCY=LENIENT METRICS_FILE=metrics.$PREFIX.txt TMP_DIR=$PREFIX\_tmp
+	java -Xmx2G -jar $MARK_DUPLICATE INPUT=$PREFIX\_tmp/$PREFIX.uniq.filtered.paired.cis.longRange.sorted.bam OUTPUT=$PREFIX.bam ASSUME_SORTED=true REMOVE_DUPLICATES=true VALIDATION_STRINGENCY=LENIENT METRICS_FILE=metrics.$PREFIX.txt TMP_DIR=$PREFIX\_tmp
 	samtools index $PREFIX.bam
 else
 	printf 'warning: %s_tmp/%s.uniq.filtered.paired.sorted.nodup.bam already exist.\n'  "$PREFIX" "$PREFIX" 2>&1 | tee -a $PREFIX.log
@@ -216,7 +244,6 @@ UNIQ_FILTERED_PAIRED_READS_CIS=$(samtools view $PREFIX\_tmp/$PREFIX.uniq.filtere
 UNIQ_FILTERED_PAIRED_READS_TRANS=$(samtools view $PREFIX\_tmp/$PREFIX.uniq.filtered.paired.trans.bam | wc -l | awk '{print $1}')
 UNIQ_FILTERED_PAIRED_READS_CIS_LONG=$(samtools view $PREFIX\_tmp/$PREFIX.uniq.filtered.paired.cis.longRange.sorted.bam | wc -l | awk '{print $1}')
 UNIQ_FILTERED_PAIRED_READS_CIS_LONG_NODUP=$(samtools view $PREFIX.bam | wc -l | awk '{print $1}')
-
 
 echo "================================ Summary ==================================" 2>&1 | tee -a $PREFIX.log
 echo "total number of reads = $((TOTAL_READS/4))" 2>&1 | tee -a $PREFIX.log
