add bin/hicpeak_filter_bait_reads

diff --git a/bin/hicpeak b/bin/hicpeak
--- a/bin/hicpeak
+++ b/bin/hicpeak
@@ -10,7 +10,8 @@ function ctrl_c() {
 
 
 # PART I check weather softwares installed
-command -v samtools >/dev/null 2>&1 || { echo >&2 "hicmap requires samtools but it's not installed.  Aborting."; exit 1; }
+command -v samtools >/dev/null 2>&1 || { echo >&2 "hicpeak requires samtools but it's not installed.  Aborting."; exit 1; }
+command -v hicpeak_filter_bait_reads >/dev/null 2>&1 || { echo >&2 "hicpeak requires hicpeak_filter_bait_reads but it's not installed.  Aborting."; exit 1; }
 
 # PART II usage info
 usage(){
@@ -128,9 +129,9 @@ echo SMOOTH_FACTOR=$SMOOTH_FACTOR 2>&1 | tee -a $PREFIX.log
 echo 2>&1 | tee -a $PREFIX.log
 
 echo -e "$REGION_CHR\t$REGION_START\t$REGION_END" > $PREFIX.bed
-samtools view -h $TREAT $REGION_CHR:$REGION_START-$REGION_END | python hicTo4c.py $REGION_WIDTH | samtools view -bS - | samtools sort - $PREFIX.treat
+samtools view -h $TREAT $REGION_CHR:$REGION_START-$REGION_END | hicpeak_filter_bait_reads $REGION_WIDTH | samtools view -bS - | samtools sort - $PREFIX.treat
 samtools index $PREFIX.treat.bam
-samtools view -h $INPUT $REGION_CHR:$REGION_START-$REGION_END | python hicTo4c.py $REGION_WIDTH | samtools view -bS - | samtools sort - $PREFIX.input
+samtools view -h $INPUT $REGION_CHR:$REGION_START-$REGION_END | hicpeak_filter_bait_reads $REGION_WIDTH | samtools view -bS - | samtools sort - $PREFIX.input
 samtools index $PREFIX.input.bam
 Rscript hicTo4c.R treat_file=\'$PREFIX.treat.bam\' input_file=\'$PREFIX.input.bam\' CHROM=\'$REGION_CHR\' START=$WINDOW_START END=$WINDOW_END step_size=$EXTEND_LEN extend_len=$EXTEND_LEN bin_size=$BIN_SIZE smooth_factor=$SMOOTH_FACTOR prefix=\'$PREFIX\'
 rm $PREFIX.treat.bam
